development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: tom
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: tom
  password:

production:
  encoding: unicode
  database: blog_production
  pool: 5
  username: tom
  password:
